version: '3.8'

services:
  web:
    image: 'node:latest'
    working_dir: /home/node/app
    volumes:
      - ./client/build/:/home/node/app
    command: sh -c "npm install -g serve && serve -l 5000 ."
    depends_on:
      - python-api
    ports:
      - '8000:5000'

  python-api:
    build: .
    env_file:
      - ./app.env
    environment:
      DB_SERVER: 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
    working_dir: /usr/src/app
    command: sh -c "sleep 5 && python manage.py db upgrade && python -m flask run --host 0.0.0.0"

  db:
    image: 'postgres:latest'
    env_file:
      - ./app.env
    ports:
      - '5432:5432'
